POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
    "username": "user4",
    "password": "changemeplese"
}

###

POST http://127.0.0.1:8000/api/jwt/create/
Content-Type: application/json

{
    "username": "user2",
    "password": "changemeplese"
}

###

GET http://127.0.0.1:8000/api/ingredients/?search=б

###

GET http://127.0.0.1:8000/api/ingredients/?name=б

###

GET http://127.0.0.1:8000/api/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3MzAxNjA4LCJpYXQiOjE3NDcyMTUyMDgsImp0aSI6IjJhMmI1MjVlNzEzNzQ1MDE5MTYzMmNhMzUyYTFiYjI2IiwidXNlcl9pZCI6MX0.LIAFjpxX8r9D2_v6C8VAp-Nz73hkXnqOb3ZS3905qPo

###

DELETE http://127.0.0.1:8000/api/users/me/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3MzAxNjA4LCJpYXQiOjE3NDcyMTUyMDgsImp0aSI6IjJhMmI1MjVlNzEzNzQ1MDE5MTYzMmNhMzUyYTFiYjI2IiwidXNlcl9pZCI6MX0.LIAFjpxX8r9D2_v6C8VAp-Nz73hkXnqOb3ZS3905qPo
Content-Type: application/json

{
    "current_password": "changemeplese"
}

###

POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
    "first_name": "Igorechek",
    "last_name": "Boring",
    "email": "ighor156@gmail.com",
    "username": "holochka2",
    "password": "changemeplese"
}

###

POST http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json

{
    "email": "ighor156@gmail.com",
    "password": "changemeplese"
}

###
POST http://localhost:8000/api/recipes/
Authorization: Token ea86ea64421b0167686950b3d0d88bbdef504660
Content-Type: application/json

{
    "cooking_time": "1",
    "ingredients": [{"id": 34, "amount": 100}, 
    {"id": 77, "amount": 125},
    {"id": 123, "amount": 150}],
    "name": "Что-то",
    "text": "С чем-то"
}

###  {"id": 100, "amount": 100}

PATCH http://localhost:8000/api/recipes/1/
Authorization: Token ea86ea64421b0167686950b3d0d88bbdef504660
Content-Type: application/json

{
    "cooking_time": "1",
    "ingredients": [
        {"id": 34, "amount": 100},
        {"id": 60, "amount": 250}],
    "name": "Апельсиновая вода два",
    "text": "Текст после изменения"
}

###

GET http://localhost:8000/api/recipes/

###

GET http://localhost:8000/api/ingredients/
Authorization: Token 1e8258755d14505c31b603c4e404a0245860c727

###

GET http://localhost:8000/api/users/
Authorization: Token 1e8258755d14505c31b603c4e404a0245860c727

###

GET http://localhost:8000/api/recipes/
Authorization: Token 1e8258755d14505c31b603c4e404a0245860c727

###

POST http://localhost:8000/api/recipes/1/shopping_cart/
Authorization: Token b3e46ab3511a2619592cc7becab8139b51214adb

###

GET http://localhost:8000/api/recipes/?is_in_shopping_cart=1
Authorization: Token b3e46ab3511a2619592cc7becab8139b51214adb

###

GET http://localhost:8000/api/recipes/download_shopping_cart/
Authorization: Token b3e46ab3511a2619592cc7becab8139b51214adb

###

GET http://localhost:8000/api/recipes/?is_favorited=1
Authorization: Token e8f6f6be459577de8080a565992377d58f68f1c7

###

GET http://localhost:8000/api/users/subscriptions/
Authorization: Token c4e43701c747dcd0db0de6d302ac57ea8dc719c4

###

GET http://localhost:8000/api/users/subscriptions/
Authorization: Token e8f6f6be459577de8080a565992377d58f68f1c7

###

POST http://localhost:8000/api/users/1/subscribe/
Authorization: Token e8f6f6be459577de8080a565992377d58f68f1c7

###

GET http://localhost:8000/api/users/subscriptions/
Authorization: Token e8f6f6be459577de8080a565992377d58f68f1c7

###

POST http://localhost:8000/api/recipes/21/favorite/
Authorization: Token e8f6f6be459577de8080a565992377d58f68f1c7

###

DELETE http://localhost:8000/api/recipes/1/favorite/
Authorization: Token e8f6f6be459577de8080a565992377d58f68f1c7
