# Generated by Django 5.2.1 on 2025-05-15 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_quantity_recipeingredient_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='unit',
            new_name='measurement_unit',
        ),
    ]
