# Generated by Django 5.2.1 on 2025-05-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_shoppinglist_recipe_alter_shoppinglist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='measurement_unit',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(),
        ),
    ]
