# Generated by Django 5.2.1 on 2025-05-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipe_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='measurement_unit',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
