# Generated by Django 5.2.1 on 2025-06-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_recipeingredient_measurement_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURLS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.URLField(unique=True)),
                ('short_url', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('requests_count', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='measurement_unit',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
