# Generated by Django 5.2.1 on 2025-06-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_shorturls_alter_recipeingredient_measurement_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturls',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='shorturls',
            name='requests_count',
        ),
        migrations.AddField(
            model_name='recipe',
            name='short_url',
            field=models.CharField(default=str, max_length=32),
            preserve_default=False,
        ),
    ]
