# Generated by Django 5.2.1 on 2025-06-02 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_remove_shorturls_is_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShortURLS',
        ),
    ]
